export const brandCars = [
  { id: 1, title: "Honda", value: "honda" },
  { id: 2, title: "Toyota", value: "Toyota" },
  { id: 3, title: "Ford", value: "ford" },
  { id: 4, title: "Nissan", value: "nissan" },
  { id: 5, title: "Chevrolet", value: "chevrolet" },
  { id: 6, title: "Volkswagen", value: "volkswagen" },
  { id: 7, title: "Hyundai", value: "hyundai" },
  { id: 8, title: "Kia", value: "kia" },
  { id: 9, title: "Fiat", value: "fiat" },
  { id: 10, title: "Mercedes Benz", value: "mercedes benz" },
  { id: 11, title: "Jaguar", value: "jaguar" },
  { id: 12, title: "BMW", value: "bmw" },
  { id: 13, title: "Audi", value: "audi" },
  { id: 14, title: "Renault", value: "renault" },
  { id: 15, title: "Peugeot", value: "peugeot" },
  { id: 16, title: "Citroen", value: "citroen" },
];
