export const brandBikes = [
  { id: 1, title: "Honda", value: "Honda" },
  { id: 2, title: "Kawasaki", value: "Kawasaki" },
  { id: 3, title: "Suzuki", value: "Suzuki" },
  { id: 4, title: "BMW", value: "Bmw" },
  { id: 5, title: "Ducati", value: "Ducati" },
  { id: 6, title: "KTM", value: "Ktm" },
  { id: 7, title: "Triumph", value: "Triumph" },
  { id: 8, title: "Harley-Davidson", value: "Harley-Davidson" },
  { id: 9, title: "Yamaha", value: "Yamaha" },
  { id: 10, title: "Dicati", value: "Ducati" },
  { id: 11, title: "Dafra", value: "Dafra" },
  { id: 12, title: "Haojue", value: "Haojue" },
  { id: 13, title: "Kymco", value: "Kymco" },
  { id: 14, title: "MXF", value: "MXF" },
  { id: 15, title: "Piaggio", value: "Piaggio" },
  { id: 16, title: "Pro Tork", value: "Pro Tork" },
  { id: 17, title: "Royal Enfield", value: "Royal Enfield" },
  { id: 18, title: "Shineray", value: "Shineray" },
];
