export const brandCars = [
  { id: 1, title: "Chevrolet", value: "Chevrolet" },
  { id: 2, title: "Fiat", value: "Fiat" },
  { id: 3, title: "Ford", value: "Ford" },
  { id: 4, title: "Hyundai", value: "Hyundai" },
  { id: 5, title: "Nissan", value: "Nissan" },
  { id: 6, title: "Renault", value: "Renault" },
  { id: 7, title: "Volkswagen", value: "Volkswagen" },
  { id: 8, title: "Toyota", value: "Toyota" },
  { id: 9, title: "Peugeot", value: "Peugeot" },
  { id: 10, title: "Citroen", value: "Citroen" },
  { id: 11, title: "Mercedes-Benz", value: "Mercedes-Benz" },
  { id: 12, title: "Bmw", value: "Bmw" },
  { id: 13, title: "Porsche", value: "Porsche" },
  { id: 14, title: "Hyundai", value: "Hyundai" },
  { id: 15, title: "Jeep", value: "Jeep" },
  { id: 16, title: "Volvo", value: "Volvo" },
  { id: 17, title: "Peugeout", value: "Peugeout" },
  { id: 18, title: "Audi", value: "Audi" },
  { id: 19, title: "Jaguar", value: "Jaguar" },
  { id: 20, title: "Chery", value: "Chery" },
  { id: 21, title: "Dodge", value: "Dodge" },
  { id: 22, title: "Ferrari", value: "Ferrari" },
  { id: 23, title: "Lamborghini", value: "Lamborghini" },
  { id: 24, title: "Kia", value: "Kia" },
  { id: 25, title: "Mazda", value: "Mazda" },
  { id: 26, title: "Mitsubishi", value: "Mitsubishi" },
  { id: 27, title: "Subaru", value: "Subaru" },
  { id: 28, title: "Suzuki", value: "Suzuki" },
  { id: 29, title: "Alfa Romeo", value: "Alfa Romeo" },
  { id: 30, title: "Aston Martin", value: "Aston Martin" },
  { id: 31, title: "Maserati", value: "Maserati" },
  { id: 32, title: "Lexus", value: "Lexus" },
  { id: 33, title: "Agrale", value: "Agrale" },
  { id: 34, title: "Bentley", value: "Bentley" },
  { id: 35, title: "Changan", value: "Changan" },
  { id: 36, title: "Chrysler", value: "Chrysler" },
  { id: 37, title: "Dacia", value: "Dacia" },
  { id: 38, title: "Effa", value: "Effa" },
  { id: 39, title: "Geely", value: "Geely" },
  { id: 40, title: "Hafei", value: "Hafei" },
  { id: 41, title: "Iveco", value: "Iveco" },
  { id: 42, title: "JAC Motors", value: "JAC-Motors" },
  { id: 43, title: "Jinbei", value: "Jinbei" },
  { id: 44, title: "Land rover", value: "Land-Rover" },
  { id: 45, title: "Lifan", value: "Lifan" },
  { id: 46, title: "Mini", value: "Mini" },
  { id: 47, title: "Troller", value: "Troller" },
  { id: 48, title: "Smart", value: "Smart" },
  { id: 49, title: "Ssangyong", value: "Ssangyong" },
  { id: 50, title: "Ram", value: "Ram" },
  { id: 51, title: "Honda", value: "Honda" },
];
