import {defineType, defineField} from 'sanity'

export const announcementType = defineType({
  name: 'announcement',
  title: 'Announcement',
  type: 'document',
  fields: [
    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
    }),
    defineField({
      name: 'link',
      title: 'Link',
      type: 'url',
    }),
    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      options: {
        list: [
          {title: 'São Paulo', value: 'São paulo'},
          {title: 'São Bernardo do Campo', value: 'São bernardo do campo'},
          {title: 'São Caetano', value: 'São caetano'},
          {title: 'Santo Andre', value: 'Santo andre'},
          {title: 'Ribeirão Pires', value: 'Ribeirão pires'},
          {title: 'Mauá', value: 'Mauá'},
        ],
      },
    }),

    defineField({
      name: 'brandCar',
      title: 'Marca do carro',
      type: 'string',
      options: {
        list: [
          {title: 'Chevrolet', value: 'Chevrolet'},
          {title: 'Fiat', value: 'Fiat'},
          {title: 'Ford', value: 'Ford'},
          {title: 'Hyundai', value: 'Hyundai'},
          {title: 'Nissan', value: 'Nissan'},
          {title: 'Renault', value: 'Renault'},
          {title: 'Volkswagen', value: 'Volkswagen'},
          {title: 'Toyota', value: 'Toyota'},
          {title: 'Peugeot', value: 'Peugeot'},
          {title: 'Citroen', value: 'Citroen'},
          {title: 'Mercedes-Benz', value: 'Mercedes-Benz'},
          {title: 'Bmw', value: 'Bmw'},
          {title: 'Porsche', value: 'Porsche'},
          {title: 'Hyundai', value: 'Hyundai'},
          {title: 'Jeep', value: 'Jeep'},
          {title: 'Volvo', value: 'Volvo'},
          {title: 'Peugeout', value: 'Peugeout'},
          {title: 'Audi', value: 'Audi'},
          {title: 'Jaguar', value: 'Jaguar'},
          {title: 'Chery', value: 'Chery'},
          {title: 'Dodge', value: 'Dodge'},
          {title: 'Ferrari', value: 'Ferrari'},
          {title: 'Lamborghini', value: 'Lamborghini'},
          {title: 'Kia', value: 'Kia'},
          {title: 'Mazda', value: 'Mazda'},
          {title: 'Mitsubishi', value: 'Mitsubishi'},
          {title: 'Subaru', value: 'Subaru'},
          {title: 'Suzuki', value: 'Suzuki'},
          {title: 'Alfa Romeo', value: 'Alfa Romeo'},
          {title: 'Aston Martin', value: 'Aston Martin'},
          {title: 'Maserati', value: 'Maserati'},
          {title: 'Lexus', value: 'Lexus'},
          {title: 'Agrale', value: 'Agrale'},
          {title: 'Bentley', value: 'Bentley'},
          {title: 'Changan', value: 'Changan'},
          {title: 'Chrysler', value: 'Chrysler'},
          {title: 'Dacia', value: 'Dacia'},
          {title: 'Effa', value: 'Effa'},
          {title: 'Geely', value: 'Geely'},
          {title: 'Hafei', value: 'Hafei'},
          {title: 'Iveco', value: 'Iveco'},
          {title: 'JAC Motors', value: 'JAC-Motors'},
          {title: 'Jinbei', value: 'Jinbei'},
          {title: 'Land rover', value: 'Land-Rover'},
          {title: 'Lifan', value: 'Lifan'},
          {title: 'Mini', value: 'Mini'},
          {title: 'Troller', value: 'Troller'},
          {title: 'Smart', value: 'Smart'},
          {title: 'Ssangyong', value: 'Ssangyong'},
          {title: 'Ram', value: 'Ram'},
          {title: 'Honda', value: 'Honda'},
          {title: 'Yamaha', value: 'Yamaha'},
          {title: 'Kawasaki', value: 'Kawasaki'},
          {title: 'Suzuki', value: 'Suzuki'},
          {title: 'BMW', value: 'Bmw'},
          {title: 'Ducati', value: 'Ducati'},
          {title: 'KTM', value: 'Ktm'},
          {title: 'Harley-Davidson', value: 'Harley-Davidson'},
          {title: 'Triumph', value: 'Triumph'},
          {title: 'Dicati', value: 'Ducati'},
          {title: 'Dafra', value: 'Dafra'},
          {title: 'Haojue', value: 'Haojue'},
          {title: 'Kymco', value: 'Kymco'},
          {title: 'MXF', value: 'MXF'},
          {title: 'Piaggio', value: 'Piaggio'},
          {title: 'Pro Tork', value: 'Pro Tork'},
          {title: 'Royal Enfield', value: 'Royal Enfield'},
          {title: 'Shineray', value: 'Shineray'},
        ],
      },
    }),

    defineField({
      name: 'model',
      title: 'Model',
      type: 'string',
    }),

    defineField({
      name: 'price',
      title: 'Price',
      type: 'number',
    }),
    defineField({
      name: 'fuel',
      title: 'Fuel',
      type: 'string',
      options: {
        list: [
          {title: 'Flex', value: 'flex'},
          {title: 'Gasolina', value: 'gasolina'},
          {title: 'Etanol', value: 'etanol'},
          {title: 'GPL', value: 'gpl'},
          {title: 'Diesel', value: 'diesel'},
          {title: 'Eletrico', value: 'eletrico'},
        ],
      },
    }),

    defineField({
      name: 'year',
      title: 'Year',
      type: 'number',
      options: {
        list: Array.from({length: 50}, (_, i) => {
          const year = new Date().getFullYear() - i
          return {title: year.toString(), value: year}
        }),
      },
    }),
    defineField({
      name: 'km',
      title: 'Km',
      type: 'number',
    }),
  ],
})
