export const initialFilters = {
  brandCar: "",
  modelCar: "",
  location: "",
  fuel: "",
  exchange: "",
  doors: 0,
  color: "",
  minPrice: 0,
  maxPrice: 0,
  announce: "",
  km: 0,
  bodyType: "",
  accessories: [],
  startYear: 0,
  endYear: 0,
  motors: 0,
  mechanic: "",
};
